services:
  whois-domain-lookup:
    container_name: whois-domain-lookup
    image: reg233/whois-domain-lookup:latest
    environment:
      DEFAULT_EXTENSION: ""
      SITE_PASSWORD: "aG9@jM3!vR5sE*qP8wT2bC6k"
      BASE: "/whois/"
      HOSTED_ON: "whois-domain-lookup.fincident"
      HOSTED_ON_URL: "https://whois-domain-lookup.fincident.org"
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
